version: '3.9'

services:
  chirpstack-create-api-key:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chirpstack-create-api-key
    ports:
      - "3000:3000"
      - "6080:6080"
    volumes:
      - browser_state:/app/user-data
    environment:
      - NODE_ENV=production

volumes:
  browser_state: